# Generated by Django 4.1.1 on 2022-09-07 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('idArticulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('descripcion', models.CharField(max_length=30, verbose_name='descripcion')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('imagen', models.ImageField(upload_to='media', verbose_name='imagen')),
                ('color', models.CharField(max_length=30, verbose_name='color')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoCompra',
            fields=[
                ('idCarritoCompra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
                ('precioTotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('idArticulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.articulo')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioAdmin',
            fields=[
                ('idUsuarioAdmin', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='nombres')),
                ('apellido', models.CharField(max_length=30, verbose_name='apellidos')),
                ('correo', models.EmailField(max_length=254, verbose_name='correo')),
                ('contraseña', models.CharField(max_length=15, verbose_name='contraseña')),
                ('rol', models.CharField(choices=[('Cliente', 'Cliente'), ('Administrador', 'Administrador')], default='administrador', max_length=30, verbose_name='rol')),
            ],
            options={
                'verbose_name': 'UsuarioAdmin',
                'verbose_name_plural': 'UsuarioAdmins',
                'db_table': 'UsuarioAdmin',
                'ordering': ['idUsuarioAdmin'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioCliente',
            fields=[
                ('idUsuarioCliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='nombres')),
                ('apellido', models.CharField(max_length=30, verbose_name='apellidos')),
                ('correo', models.EmailField(max_length=254, verbose_name='correo')),
                ('contraseña', models.CharField(max_length=15, verbose_name='contraseña')),
                ('rol', models.CharField(choices=[('Cliente', 'Cliente'), ('Administrador', 'Administrador')], default='cliente', max_length=30, verbose_name='rol')),
            ],
            options={
                'verbose_name': 'UsuarioCliente',
                'verbose_name_plural': 'UsuarioClientes',
                'db_table': 'UsuarioCliente',
                'ordering': ['idUsuarioCliente'],
            },
        ),
        migrations.CreateModel(
            name='Invetario',
            fields=[
                ('idInventario', models.AutoField(primary_key=True, serialize=False)),
                ('idArticulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.articulo')),
                ('idUsuarioAdmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.usuarioadmin')),
            ],
            options={
                'verbose_name': 'Invetario',
                'verbose_name_plural': 'Invetarios',
                'db_table': 'Invetario',
                'ordering': ['idInventario'],
            },
        ),
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('idFacturacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('precioFinal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idCarritoCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.carritocompra')),
            ],
        ),
        migrations.AddField(
            model_name='carritocompra',
            name='idUsuarioCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.usuariocliente'),
        ),
    ]
