# Generated by Django 4.1 on 2022-09-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_remove_articulo_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['idArticulo'], 'verbose_name': 'Articulo', 'verbose_name_plural': 'Articulos'},
        ),
        migrations.AlterModelOptions(
            name='carritocompra',
            options={'ordering': ['idCarritoCompra'], 'verbose_name': 'CarritoCompra', 'verbose_name_plural': 'CarritoCompras'},
        ),
        migrations.AlterModelOptions(
            name='facturacion',
            options={'ordering': ['idFacturacion'], 'verbose_name': 'Facturacion', 'verbose_name_plural': 'Facturacions'},
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precio',
            field=models.IntegerField(verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='carritocompra',
            name='precioTotal',
            field=models.IntegerField(verbose_name='precioTotal'),
        ),
        migrations.AlterField(
            model_name='facturacion',
            name='fecha',
            field=models.DateField(auto_now=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='facturacion',
            name='precioFinal',
            field=models.IntegerField(verbose_name='precioFinal'),
        ),
        migrations.AlterModelTable(
            name='articulo',
            table='Articulo',
        ),
        migrations.AlterModelTable(
            name='carritocompra',
            table='CarritoCompra',
        ),
        migrations.AlterModelTable(
            name='facturacion',
            table='Facturacion',
        ),
    ]
