# Generated by Django 4.1 on 2022-09-08 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0003_alter_articulo_options_alter_carritocompra_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invetario',
            new_name='Inventario',
        ),
        migrations.AlterModelOptions(
            name='inventario',
            options={'ordering': ['idInventario'], 'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventarios'},
        ),
        migrations.AlterModelTable(
            name='inventario',
            table='Inventario',
        ),
    ]
