# Generated by Django 4.1.1 on 2022-11-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0006_usuariocliente_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='descripcion'),
        ),
    ]
